apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aiops-prod-argo

commonLabels:
  app.kubernetes.io/component: solgate
  app.kubernetes.io/part-of: data-hub
  app.kubernetes.io/managed-by: aicoe-aiops-devops-argocd

resources:
  - ../../base
  - ./usir
